version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_DB=PingTowerBase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4230
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-database/:/docker-entrypoint-initdb.d/
    ports:
      - "5430:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d PingTowerBase"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  spectator:
    build: ./SpectatorService
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=PingTowerBase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4230
    networks:
      - app-network

  client-handler:
    build: ./ClientHandlerService
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=PingTowerBase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4230
    ports:
      - "80:8080"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge