version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  spectator:
    build: SpectatorServices
    depends_on:
      - postgres
    ports:
      - "5430:5432"